#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : ktp-desktop-applets
Version  : 19.08.0
Release  : 11
URL      : https://download.kde.org/stable/applications/19.08.0/src/ktp-desktop-applets-19.08.0.tar.xz
Source0  : https://download.kde.org/stable/applications/19.08.0/src/ktp-desktop-applets-19.08.0.tar.xz
Source1 : https://download.kde.org/stable/applications/19.08.0/src/ktp-desktop-applets-19.08.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 LGPL-2.1
Requires: ktp-desktop-applets-data = %{version}-%{release}
Requires: ktp-desktop-applets-lib = %{version}-%{release}
Requires: ktp-desktop-applets-license = %{version}-%{release}
Requires: ktp-desktop-applets-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : plasma-framework-dev
BuildRequires : qtbase-dev mesa-dev

%description
No detailed description available

%package data
Summary: data components for the ktp-desktop-applets package.
Group: Data

%description data
data components for the ktp-desktop-applets package.


%package lib
Summary: lib components for the ktp-desktop-applets package.
Group: Libraries
Requires: ktp-desktop-applets-data = %{version}-%{release}
Requires: ktp-desktop-applets-license = %{version}-%{release}

%description lib
lib components for the ktp-desktop-applets package.


%package license
Summary: license components for the ktp-desktop-applets package.
Group: Default

%description license
license components for the ktp-desktop-applets package.


%package locales
Summary: locales components for the ktp-desktop-applets package.
Group: Default

%description locales
locales components for the ktp-desktop-applets package.


%prep
%setup -q -n ktp-desktop-applets-19.08.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1565910416
mkdir -p clr-build
pushd clr-build
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1565910416
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ktp-desktop-applets
cp COPYING %{buildroot}/usr/share/package-licenses/ktp-desktop-applets/COPYING
cp COPYING.LIB %{buildroot}/usr/share/package-licenses/ktp-desktop-applets/COPYING.LIB
cp cmake/modules/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/ktp-desktop-applets/cmake_modules_COPYING-CMAKE-SCRIPTS
pushd clr-build
%make_install
popd
%find_lang plasma_applet_org.kde.ktp-chat
%find_lang plasma_applet_org.kde.person
%find_lang plasma_applet_org.kde.ktp-contactlist

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/kservices5/plasma-applet-org.kde.ktp-chat.desktop
/usr/share/kservices5/plasma-applet-org.kde.ktp-contactlist.desktop
/usr/share/kservices5/plasma-applet-org.kde.person.desktop
/usr/share/plasma/plasmoids/org.kde.ktp-chat/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.ktp-chat/contents/ui/ActionDelegate.qml
/usr/share/plasma/plasmoids/org.kde.ktp-chat/contents/ui/ChatWidget.qml
/usr/share/plasma/plasmoids/org.kde.ktp-chat/contents/ui/ConversationDelegate.qml
/usr/share/plasma/plasmoids/org.kde.ktp-chat/contents/ui/ConversationDelegateButton.qml
/usr/share/plasma/plasmoids/org.kde.ktp-chat/contents/ui/FullChatList.qml
/usr/share/plasma/plasmoids/org.kde.ktp-chat/contents/ui/OutgoingDelegate.qml
/usr/share/plasma/plasmoids/org.kde.ktp-chat/contents/ui/TextDelegate.qml
/usr/share/plasma/plasmoids/org.kde.ktp-chat/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.ktp-chat/metadata.desktop
/usr/share/plasma/plasmoids/org.kde.ktp-contactlist/contents/ui/ContactList.qml
/usr/share/plasma/plasmoids/org.kde.ktp-contactlist/contents/ui/ListContactDelegate.qml
/usr/share/plasma/plasmoids/org.kde.ktp-contactlist/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.ktp-contactlist/metadata.desktop
/usr/share/plasma/plasmoids/org.kde.person/contents/config/config.qml
/usr/share/plasma/plasmoids/org.kde.person/contents/config/main.xml
/usr/share/plasma/plasmoids/org.kde.person/contents/ui/Person.qml
/usr/share/plasma/plasmoids/org.kde.person/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.person/contents/ui/settingsGeneral.qml
/usr/share/plasma/plasmoids/org.kde.person/metadata.desktop

%files lib
%defattr(-,root,root,-)
/usr/lib64/qt5/qml/org/kde/ktpchat/libktpchatplugin.so
/usr/lib64/qt5/qml/org/kde/ktpchat/qmldir
/usr/lib64/qt5/qml/org/kde/ktpcontactlist/libktpcontactlistplugin.so
/usr/lib64/qt5/qml/org/kde/ktpcontactlist/qmldir

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ktp-desktop-applets/COPYING
/usr/share/package-licenses/ktp-desktop-applets/COPYING.LIB
/usr/share/package-licenses/ktp-desktop-applets/cmake_modules_COPYING-CMAKE-SCRIPTS

%files locales -f plasma_applet_org.kde.ktp-chat.lang -f plasma_applet_org.kde.person.lang -f plasma_applet_org.kde.ktp-contactlist.lang
%defattr(-,root,root,-)

